### ISSUE TITLE
[C4GT Community]: Dockerize AMRIT Platform

### ISSUE THREAD

**Issue by drtechie** [PSMRI/AMRIT#59]
## Description
AMRIT Platform consists of several service lines. Service lines are split into a UI frontend and an associated API backend. In addition to these UI-API pairs, you will find additional microservices common across service line specific API services. You will find the list of repos and services in [AMRIT](https://github.com/PSMRI/AMRIT/) repo README.  

We have created a docker-compose.yml file for setting up infra of AMRIT platform. This ticket is a continuation of the process. 

Create a production-ready containerized system for multiple Angular UI applications and Spring Boot microservices using Docker and Nginx reverse proxy. The solution should enable secure communication between frontend and backend services while maintaining isolated environments and efficient resource utilization.

## Goals
- [ ] Dockerize Angular UI applications with Nginx serving static assets
- [ ] Create Docker images for Spring Boot microservices
- [ ] Configure Nginx reverse proxy for API routing
- [ ] Implement Docker Compose for multi-service orchestration
- [ ] Document setup and deployment process

### Expected Outcome

- Multiple Docker containers running in isolated network environments
- Angular applications accessible via unified domain with path-based routing
- API endpoints proxied through Nginx with proper CORS configuration
- Automated build process using multi-stage Dockerfiles
- Health-check endpoints for all services

### Acceptance Criteria

1. All services start successfully via `docker-compose up`  
2. UI applications remain functional after page refresh  
3. API response time < 500ms through Nginx proxy  
4. Zero hard-coded IP addresses in configuration  
5. Pass security scan with `docker scan`  
6. Comprehensive logging for inter-service communication
7. Add secrets and keys must be managed in .env or relevant environment configuration

### Implementation Details

Dockerization Strategy for Spring Boot Microservices
Individual Docker Images per Service
Each microservice requires its own Dockerfile for isolation and scalability:

Network Configuration
Use separate networks for frontend/backend segregation
Allow cross-network communication for UI-to-API access

For UI services, each UI build files must be added in nginx root.

Example implementation details

**Dockerfile**
```
# Stage 1: Build Angular Applications
FROM node:16-alpine AS builder

WORKDIR /usr/src/app

# Build UI app1
# Clone and build UI app1

# Build UI app2
# Clone and build UI app2

# Stage 2: Serve with Nginx
FROM nginx:alpine

# Remove default Nginx configuration
RUN rm /etc/nginx/conf.d/default.conf

# Copy custom Nginx configuration
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Copy built Angular apps to Nginx HTML directory
COPY --from=builder /usr/src/app/dist/app1 /usr/share/nginx/html/app1
COPY --from=builder /usr/src/app2/dist/app2 /usr/share/nginx/html/app2

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]

```

**Docker compose**
```
version: '3.8'
services:
  # Spring Boot Microservices
  hwc-service:
    build: ./hwc-service
    ports:
      - "8081:8080"
    networks:
      - backend
    depends_on:
      mysql:
        condition: service_healthy

  common-api-service:
    build: ./common-api-service
    ports:
      - "8082:8080"
    networks:
      - backend

  # Angular UI
  angular-ui:
    build: ./angular-ui
    ports:
      - "80:80"
    networks:
      - frontend
      - backend

networks:
  frontend:
  backend:

volumes:
  # for mongo, mysql and redis

```

Nginx reverse proxy config

```
server {
    listen 80;
    
    # Serve Angular App
    location / {
        root /usr/share/nginx/html;
        try_files $uri $uri/ /index.html;
    }

    # Proxy API Requests
    location /api/hwc {
        resolver 127.0.0.11 valid=30s;  # Docker DNS
        proxy_pass http://hwc-api-service:8080/api;
        proxy_set_header Host $host;
    }

    location /api/common {
        resolver 127.0.0.11 valid=30s;  # Docker DNS
        proxy_pass http://common-api-service:8081/api;
        proxy_set_header Host $host;
    }
}

```

### Mockups/Wireframes

NA

### Product Name

AMRIT

### Organisation Name

Piramal Swasthya Management and Research Institute

### Domain

Healthcare

### Tech Skills Needed

Docker, DevOps, Spring Boot, Angular

### Organizational Mentor

@drtechie 

### Complexity

High

### Category

Delpoyment
